spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
<<<<<<< HEAD
    change-log: db/changeLog/create_local.sql
=======
    change-log: db/changeLog/db.changelog-master_local.yaml
>>>>>>> task-2_
