spring:
  datasource:
    username: postgres
    password: 18011984
    url: jdbc:postgresql://localhost/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  main:
    allow-circular-references: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
server:
  servlet:
    context-path: "/api/v1"

