spring:
  datasource:
    username: postgres
    password: 18011984
    url: jdbc:postgresql://localhost/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  data:
    web:
      pageable:
        one-indexed-parameters: true
  liquibase:
    change-log: db/changeLog/db.changelog-master.yaml
server:
  servlet:
    context-path: "/api"
