spring:
  datasource:
    username: postgres
    password: 18011984
    url: jdbc:postgresql://localhost/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
