spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  liquibase:
    change-log: db/changeLog/db.changelog-master.yaml
server:
  servlet:
    context-path: "/api"
  host: "localhost"
  sourcePort: 9901, 9902, 9903

